### ISSUE TITLE
Import your mod to Minecraft China

### ISSUE THREAD

**Issue by Jerry1145yard** [Lance5057/Butchercraft#102]
There is a lack of mods in the Chinese version of Minecraft JAVA Edition, can you use it with me for commercial purposes to transfer to the Chinese version of Minecraft? I will keep your chats with me confidential (to get approval) and credit you as the original author.

**Comment by Lance5057** [comment]
Commercial use of my code or art is strictly prohibited by the license that this mod falls under.

**Comment by Jerry1145yard** [comment]
You misunderstood, it's not what you think, I'm not using your MOD for commercial purposes, reprinting it on the Chinese version of the platform for commercial reprinting, not using your code and art for commercial purposes, I'm just a mod

**Comment by Lance5057** [comment]
I don't understand what you're asking then

**Comment by Jerry1145yard** [comment]
![mod](https://github.com/user-attachments/assets/45b1cae4-c8a3-45ff-8aa1-139754722a04)

**Comment by Lance5057** [comment]
could you type your question in chinese for me, might make this easier

**Comment by Jerry1145yard** [comment]
好的我来自中国我想将您的MOD上传到中国版平台，需要经过您的同意，请问可以吗？

**Comment by Lance5057** [comment]
Will you or anyone else be making money off of it?

您或其他任何人会从中赚钱吗？

**Comment by Jerry1145yard** [comment]
不它将是免费的并且表明原作者

**Comment by Jerry1145yard** [comment]
在中国版中货币有绿宝石和钻石，绿宝石是免费，钻石要付费，但是我选择什么都不要既不要绿宝石也更不会要钻石的

**Comment by Lance5057** [comment]
As long as it's free and you follow the license yes you're allowed. Do note that the license requires that you provide the license when you post the mod. You can use this link: [License](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)
The license on the github page seems to have gotten broken, I'll fix this.

**Comment by Jerry1145yard** [comment]
ok thanks!
