### ISSUE TITLE
Mod textures do NOT load

### ISSUE THREAD

**Issue by this-is-kinda-sad** [Lance5057/Butchercraft#19]
For the 1.12.2 version of ButcherCraft, it seems that the textures for all the items don't load. This results in the default pink checkered square instead of any actual textures. This is a huge issue you need to fix

**Comment by Lance5057** [comment]
"This is a huge issue you need to fix." - You should learn some basic etiquette so you don't make yourself look like an ass online. I'll fix the issues when I have time to do so.
