### ISSUE TITLE
Hooked Sheep won't go past skinning phase.

### ISSUE THREAD

**Issue by NotAPotter** [Lance5057/Butchercraft#33]
You skin, but then they won't respond to gutting knife. Does not happen to cow and pig carcass, far as I'm aware.

**Comment by Lance5057** [comment]
Seems the knife types got swapped around, the bone saw should be displayed not the gut knife.

**Comment by Screamermod** [comment]
Seems the gutting and deboning phases got swapped around. Phase two is done with the bone saw, but you get the guts, then phase 3 is done with the gutting knife, and you get the bone drops.
