### ISSUE TITLE
REQUEST actually

### ISSUE THREAD

**Issue by ZAKsPop** [Lance5057/Butchercraft#38]
Could you perhaps make it work with Cooking for Blockheads and not require Farmer's Delight? Not sure why this required Farmers Delight specifically but I prefer CFB and they both sorta do similar things. Because this mod rocks. I've always hated killing a cow for a couple steaks. Just don't want redundant mods in my pack. Thanks for such a cool mod and I like how you implemented the butchering process. Hopefully later there can be a way to add other animals. Like from Alex's mobs etc. Maybe by using datapacks.
Thanks and Happy New Year!

**Comment by Lance5057** [comment]
FD is no longer required
