### ISSUE TITLE
1.19.2 failure

### ISSUE THREAD

**Issue by akshy1405** [Lance5057/Butchercraft#39]
Hello!
Right now my game crashes if I either look up my inventory or else, I'm breeding animals with the mod installed, and then this appears on my screen:

Error code -1
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot read field "f_19853_" because the return value of "net.minecraftforge.event.entity.living.BabyEntitySpawnEvent.getCausedByPlayer()" is null

I made a full check and the only mod provoking this issue is this one, can you help me out please?

**Comment by akshy1405** [comment]
[crash-2023-01-29_21.13.10-server.txt](https://github.com/Lance5057/Butchercraft/files/10531684/crash-2023-01-29_21.13.10-server.txt)

**Comment by Lance5057** [comment]
Forgot a null check, whoops
