### ISSUE TITLE
Minor visual bugs and can't craft items

### ISSUE THREAD

**Issue by CreativeManul** [Lance5057/Butchercraft#44]
The butcher block has no object textures. Untitled block of cheese and butter (link to object) butchercraft-2.2.1 - for 1.19.2
and Also, I can't craft items in my build with this mod.

**Comment by Lance5057** [comment]
Yeah they're WIP items that got released early for a bug fix.

**Comment by CreativeManul** [comment]
I meant ALL items in the game. Even the workbench cannot be placed when the mod is installed in the modpack.

**Comment by Lance5057** [comment]
You'll have to check the mod on its own, sounds like some kind of conflict between other mods.
