### ISSUE TITLE
Suggestion: A Carcass API

### ISSUE THREAD

**Issue by elifoster** [Lance5057/Butchercraft#5]
Right now, you hard code the carcass processing code/drops directly into the Meat Hook TE. I would propose adding an interface, `Carcass` (or `ICarcass` if you like that style MC uses), which adds the methods returning lists of ItemStacks (referred to in the code base as `returns`) for each progression stage (skinning, organs, sawing, and finally butchering). Then, of course, you would remove all of those hard coded lists with calls to the interface.

**Comment by elifoster** [comment]
Looking a bit more, we'll need an API for rendering, too.

**Comment by darthvader45** [comment]
An API is planned.
