### ISSUE TITLE
butcher block and kubejs

### ISSUE THREAD

**Issue by CosmosFury13** [Lance5057/Butchercraft#66]
when i have the mod installed kubejs doesn't work and in the logs it looks like its the butcher block

**Comment by KingAurum** [comment]
I have the same problem, but looking at the logs it's the way the recipes were implemented (maybe?).
![image](https://github.com/Lance5057/Butchercraft/assets/37921713/dfe94868-3cb6-4c3a-bb2e-01ad60d34121)
