### ISSUE TITLE
[Suggestion] Butchering improvements

### ISSUE THREAD

**Issue by BlackTalons** [Lance5057/Butchercraft#67]
There are many meat cuts that could be abstracted into existing items, freeing inventory clutter.
Cubed meat and stew meat should drop as the common beef/porkchop/mutton. It's implied in most recipes that meat gets apropiatedly cut up when cooked into stew or similar dishes. Scraps and ground meats could all be grouped into minced meat.

Ribs have very little use if cut up, there's no need for individual rib items. Alternatively, all ribs could be a single item, and the Rack of Lamb would simply require mutton chops to indicate its made of lamb. 

Tongue and horns have no use that I know of, they could be removed until they are useful.

Butchering a pig should yield some ham, otherwise one has to choose between butchering it or wasting most of the meat for a chance of ham.

**Comment by Lance5057** [comment]
Ham cuts are being added, the rest no.
