### ISSUE TITLE
[1.19.2] Crash when throwing stacks of cow materials on the ground?

### ISSUE THREAD

**Issue by togera13** [Lance5057/Butchercraft#68]
[crash-2023-11-02_10.08.45-client.txt](https://github.com/Lance5057/Butchercraft/files/13239760/crash-2023-11-02_10.08.45-client.txt)
I don't know if this was specifically caused by this mod or not, but it happened when I was trying out the mod & decided to drop everything I got from carving up a cow onto the ground so I could try out bowl-able items I placed.

The part where it is mentioning sound makes me think it could possibly have something to do with sound physics remastered or ambient sounds, but I have never had a crash from dropping items with them up until this mod.

I think I dropped sinew or some other stringy looking item last before it happened.

**Comment by Lance5057** [comment]
This isn't caused by me.
