### ISSUE TITLE
butchercraft to the latest version the game crash 

### ISSUE THREAD

**Issue by Periam** [Lance5057/Butchercraft#90]
After updating butchercraft to the latest version the game crash starting.
Minecraft Version: 1.19.2
butchercraft-2.3.16.jar

Crash log
[crash-2024-05-29_18.25.19-fml.txt](https://github.com/Lance5057/Butchercraft/files/15491022/crash-2024-05-29_18.25.19-fml.txt)

**Comment by brisingraerowing** [comment]
#89
