### ISSUE TITLE
No drying rack recipe

### ISSUE THREAD

**Issue by Rundris** [Lance5057/Butchercraft#98]
Hi, 

I am playing version 1.20.1 and there is no way to make the drying rack, or the blood drain.

Installing the latest version of Butcher's Delight adds in a different drying rack recipe that works fine and doesn't use string, but then that mod introduces a compatibility that prevent all animal carcasses except the sheep carcass from being hung on the meat hook.

**Comment by unilock** [comment]
Butchercraft doesn't have a "blood drain"... are you sure you're using the right mod?
